version: '3.2'
services:
  app:
    container_name: flask_api
    build: 
      context: .
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - "4000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      backend_net:
        aliases:
          - flask_net

  
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: mysql_db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pr@ct1c@
      MYSQL_DATABASE: "store"
      MYSQL_USER: "emilio"
      MYSQL_PASSWORD: "pr@ct1c@"
    volumes:
      - ./schemas:/var/lib/mysql
    networks:
      backend_net:
        aliases:
          - mysql_net
volumes:
  schemas: {}
  
networks:
  backend_net:
    name: flask_back_net
    driver: bridge
    ipam: 
      driver: default